// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Google.UITestFramework.UIMaps.AdvertisementClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public partial class AdGroup
    {
        
        /// <summary>
        /// ClickAddAdGroupButton
        /// </summary>
        public void ClickAddAdGroupButton()
        {
            #region Variable Declarations
            WinTabPage uIAdGroups0TabPage = this.UIWss_adsagetest163comWindow.UIItemTabList.UIAdGroups0TabPage;
            WinButton uIAddAdGroupButton = this.UIWss_adsagetest163comWindow.UIRibbonToolBar.UIAddAdGroupButton;
            WinButton uIOKButton = this.UIChooseaCampaignWindow.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Ad Groups(0)' tab
            Mouse.Click(uIAdGroups0TabPage, new Point(40, 2));

            // Click 'Add Ad Group' button
            Mouse.Click(uIAddAdGroupButton, new Point(15, 24));

            // Click 'OK' button
            bool isOkWindowExist = UIChooseaCampaignWindow.UIOKWindow.WaitForControlExist();
            if(isOkWindowExist)
            {
                Mouse.Click(uIOKButton, new Point(42, 14));
            }
        }
        
        /// <summary>
        /// ClickDeleteAdGroupButton
        /// </summary>
        public void ClickDeleteAdGroupButton()
        {
            #region Variable Declarations
            WinTabPage uIAdGroupsTabPage = this.UIWss_adsagetest163comWindow.UIRibbonTabsTabList.UIAdGroupsTabPage;
            WinButton uIDeleteButton = this.UIWss_adsagetest163comWindow.UIRibbonToolBar1.UIDeleteButton;
            #endregion

            // Click 'Ad Groups' tab
            Mouse.Click(uIAdGroupsTabPage, new Point(38, 15));

            // Click 'Delete' button
            Mouse.Click(uIDeleteButton, new Point(15, 27));
        }
        
        /// <summary>
        /// ClickCampaign1Tab
        /// </summary>
        public void ClickCampaign1Tab()
        {
            #region Variable Declarations
            WinTabPage uICampaigns1TabPage = this.UIWss_adsagetest163comWindow.UIItemTabList.UICampaigns1TabPage;
            #endregion

            // Click 'Campaigns(1)' tab
            Mouse.Click(uICampaigns1TabPage, new Point(38, 9));
        }
        
        #region Properties
        public UIWss_adsagetest163comWindow UIWss_adsagetest163comWindow
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow == null))
                {
                    this.mUIWss_adsagetest163comWindow = new UIWss_adsagetest163comWindow();
                }
                return this.mUIWss_adsagetest163comWindow;
            }
        }
        
        public UIChooseaCampaignWindow UIChooseaCampaignWindow
        {
            get
            {
                if ((this.mUIChooseaCampaignWindow == null))
                {
                    this.mUIChooseaCampaignWindow = new UIChooseaCampaignWindow();
                }
                return this.mUIChooseaCampaignWindow;
            }
        }
        
        public UIWss_adsagetest163comWindow1 UIWss_adsagetest163comWindow1
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow1 == null))
                {
                    this.mUIWss_adsagetest163comWindow1 = new UIWss_adsagetest163comWindow1();
                }
                return this.mUIWss_adsagetest163comWindow1;
            }
        }
        
        public UIWss_adsagetest163comWindow2 UIWss_adsagetest163comWindow2
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow2 == null))
                {
                    this.mUIWss_adsagetest163comWindow2 = new UIWss_adsagetest163comWindow2();
                }
                return this.mUIWss_adsagetest163comWindow2;
            }
        }
        
        public UIWss_adsagetest163comWindow3 UIWss_adsagetest163comWindow3
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow3 == null))
                {
                    this.mUIWss_adsagetest163comWindow3 = new UIWss_adsagetest163comWindow3();
                }
                return this.mUIWss_adsagetest163comWindow3;
            }
        }
        
        public UIWss_adsagetest163comWindow4 UIWss_adsagetest163comWindow4
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow4 == null))
                {
                    this.mUIWss_adsagetest163comWindow4 = new UIWss_adsagetest163comWindow4();
                }
                return this.mUIWss_adsagetest163comWindow4;
            }
        }
        
        public UIWss_adsagetest163comWindow5 UIWss_adsagetest163comWindow5
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow5 == null))
                {
                    this.mUIWss_adsagetest163comWindow5 = new UIWss_adsagetest163comWindow5();
                }
                return this.mUIWss_adsagetest163comWindow5;
            }
        }
        #endregion
        
        #region Fields
        private UIWss_adsagetest163comWindow mUIWss_adsagetest163comWindow;
        
        private UIChooseaCampaignWindow mUIChooseaCampaignWindow;
        
        private UIWss_adsagetest163comWindow1 mUIWss_adsagetest163comWindow1;
        
        private UIWss_adsagetest163comWindow2 mUIWss_adsagetest163comWindow2;
        
        private UIWss_adsagetest163comWindow3 mUIWss_adsagetest163comWindow3;
        
        private UIWss_adsagetest163comWindow4 mUIWss_adsagetest163comWindow4;
        
        private UIWss_adsagetest163comWindow5 mUIWss_adsagetest163comWindow5;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow : WinWindow
    {
        
        public UIWss_adsagetest163comWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        
        public UIRibbonToolBar UIRibbonToolBar
        {
            get
            {
                if ((this.mUIRibbonToolBar == null))
                {
                    this.mUIRibbonToolBar = new UIRibbonToolBar(this);
                }
                return this.mUIRibbonToolBar;
            }
        }
        
        public UIRibbonTabsTabList UIRibbonTabsTabList
        {
            get
            {
                if ((this.mUIRibbonTabsTabList == null))
                {
                    this.mUIRibbonTabsTabList = new UIRibbonTabsTabList(this);
                }
                return this.mUIRibbonTabsTabList;
            }
        }
        
        public UIRibbonToolBar1 UIRibbonToolBar1
        {
            get
            {
                if ((this.mUIRibbonToolBar1 == null))
                {
                    this.mUIRibbonToolBar1 = new UIRibbonToolBar1(this);
                }
                return this.mUIRibbonToolBar1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTabList mUIItemTabList;
        
        private UIRibbonToolBar mUIRibbonToolBar;
        
        private UIRibbonTabsTabList mUIRibbonTabsTabList;
        
        private UIRibbonToolBar1 mUIRibbonToolBar1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemTabList : WinTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinTabPage UIAdGroups0TabPage
        {
            get
            {
                if ((this.mUIAdGroups0TabPage == null))
                {
                    this.mUIAdGroups0TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUIAdGroups0TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Ad Groups(0)";
                    this.mUIAdGroups0TabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIAdGroups0TabPage;
            }
        }
        
        public WinTabPage UICampaigns1TabPage
        {
            get
            {
                if ((this.mUICampaigns1TabPage == null))
                {
                    this.mUICampaigns1TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUICampaigns1TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Campaigns(1)";
                    this.mUICampaigns1TabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUICampaigns1TabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUIAdGroups0TabPage;
        
        private WinTabPage mUICampaigns1TabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonToolBar : WinToolBar
    {
        
        public UIRibbonToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "New";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinButton UIAddAdGroupButton
        {
            get
            {
                if ((this.mUIAddAdGroupButton == null))
                {
                    this.mUIAddAdGroupButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIAddAdGroupButton.SearchProperties[WinButton.PropertyNames.Name] = "Add Ad Group";
                    this.mUIAddAdGroupButton.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIAddAdGroupButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIAddAdGroupButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonTabsTabList : WinTabList
    {
        
        public UIRibbonTabsTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTabList.PropertyNames.Name] = "Ribbon Tabs";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinTabPage UIAdGroupsTabPage
        {
            get
            {
                if ((this.mUIAdGroupsTabPage == null))
                {
                    this.mUIAdGroupsTabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUIAdGroupsTabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Ad Groups";
                    this.mUIAdGroupsTabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIAdGroupsTabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUIAdGroupsTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonToolBar1 : WinToolBar
    {
        
        public UIRibbonToolBar1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Delete";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDeleteButton.SearchProperties[WinButton.PropertyNames.Name] = "Delete";
                    this.mUIDeleteButton.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIDeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIChooseaCampaignWindow : WinWindow
    {
        
        public UIChooseaCampaignWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Choose a Campaign";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Choose a Campaign");
            #endregion
        }
        
        #region Properties
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "BTOK";
            this.WindowTitles.Add("Choose a Campaign");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Choose a Campaign");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow1 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UITBNameWindow UITBNameWindow
        {
            get
            {
                if ((this.mUITBNameWindow == null))
                {
                    this.mUITBNameWindow = new UITBNameWindow(this);
                }
                return this.mUITBNameWindow;
            }
        }
        
        public UITBMaximumCPMBidWindow UITBMaximumCPMBidWindow
        {
            get
            {
                if ((this.mUITBMaximumCPMBidWindow == null))
                {
                    this.mUITBMaximumCPMBidWindow = new UITBMaximumCPMBidWindow(this);
                }
                return this.mUITBMaximumCPMBidWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UITBNameWindow mUITBNameWindow;
        
        private UITBMaximumCPMBidWindow mUITBMaximumCPMBidWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "16";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public UIRow1Row UIRow1Row
        {
            get
            {
                if ((this.mUIRow1Row == null))
                {
                    this.mUIRow1Row = new UIRow1Row(this);
                }
                return this.mUIRow1Row;
            }
        }
        
        public UINewItemRowRow UINewItemRowRow
        {
            get
            {
                if ((this.mUINewItemRowRow == null))
                {
                    this.mUINewItemRowRow = new UINewItemRowRow(this);
                }
                return this.mUINewItemRowRow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        
        private UIRow1Row mUIRow1Row;
        
        private UINewItemRowRow mUINewItemRowRow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemTable : WinTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinClient UIDataPanelClient
        {
            get
            {
                if ((this.mUIDataPanelClient == null))
                {
                    this.mUIDataPanelClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIDataPanelClient.SearchProperties[WinControl.PropertyNames.Name] = "Data Panel";
                    this.mUIDataPanelClient.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUIDataPanelClient;
            }
        }
        
        public UIHeaderPanelClient UIHeaderPanelClient
        {
            get
            {
                if ((this.mUIHeaderPanelClient == null))
                {
                    this.mUIHeaderPanelClient = new UIHeaderPanelClient(this);
                }
                return this.mUIHeaderPanelClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIDataPanelClient;
        
        private UIHeaderPanelClient mUIHeaderPanelClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIHeaderPanelClient : WinClient
    {
        
        public UIHeaderPanelClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinRowHeader UIItemRowHeader
        {
            get
            {
                if ((this.mUIItemRowHeader == null))
                {
                    this.mUIItemRowHeader = new WinRowHeader(this);
                    #region Search Criteria
                    this.mUIItemRowHeader.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUIItemRowHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinRowHeader mUIItemRowHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRow1Row : WinRow
    {
        
        public UIRow1Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "Row 1";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinCell UI___qQ34N3Cell
        {
            get
            {
                if ((this.mUI___qQ34N3Cell == null))
                {
                    this.mUI___qQ34N3Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUI___qQ34N3Cell.SearchProperties[WinCell.PropertyNames.Value] = "___qQ34N3";
                    this.mUI___qQ34N3Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUI___qQ34N3Cell;
            }
        }
        
        public WinCell UITestCell
        {
            get
            {
                if ((this.mUITestCell == null))
                {
                    this.mUITestCell = new WinCell(this);
                    #region Search Criteria
                    this.mUITestCell.SearchProperties[WinCell.PropertyNames.Value] = "test";
                    this.mUITestCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUITestCell;
            }
        }
        
        public WinCell UIActiveCell
        {
            get
            {
                if ((this.mUIActiveCell == null))
                {
                    this.mUIActiveCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIActiveCell.SearchProperties[WinCell.PropertyNames.Value] = "Active";
                    this.mUIActiveCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUIActiveCell;
            }
        }
        
        public WinCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[WinCell.PropertyNames.Value] = "-";
                    this.mUIItemCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        
        public WinCell UIItemCell1
        {
            get
            {
                if ((this.mUIItemCell1 == null))
                {
                    this.mUIItemCell1 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItemCell1.SearchProperties[WinCell.PropertyNames.Value] = "-";
                    this.mUIItemCell1.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUIItemCell1;
            }
        }
        
        public WinCell UIItem0Cell
        {
            get
            {
                if ((this.mUIItem0Cell == null))
                {
                    this.mUIItem0Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUIItem0Cell;
            }
        }
        
        public WinCell UIItem000Cell
        {
            get
            {
                if ((this.mUIItem000Cell == null))
                {
                    this.mUIItem000Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem000Cell.SearchProperties[WinCell.PropertyNames.Value] = "0.00%";
                    this.mUIItem000Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUIItem000Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUI___qQ34N3Cell;
        
        private WinCell mUITestCell;
        
        private WinCell mUIActiveCell;
        
        private WinCell mUIItemCell;
        
        private WinCell mUIItemCell1;
        
        private WinCell mUIItem0Cell;
        
        private WinCell mUIItem000Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UINewItemRowRow : WinRow
    {
        
        public UINewItemRowRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "NewItem Row";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinCell UICampaignrow214748364Cell
        {
            get
            {
                if ((this.mUICampaignrow214748364Cell == null))
                {
                    this.mUICampaignrow214748364Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUICampaignrow214748364Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUICampaignrow214748364Cell;
            }
        }
        
        public WinCell UIDisplayNetworkMaxCPCCell
        {
            get
            {
                if ((this.mUIDisplayNetworkMaxCPCCell == null))
                {
                    this.mUIDisplayNetworkMaxCPCCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIDisplayNetworkMaxCPCCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUIDisplayNetworkMaxCPCCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUICampaignrow214748364Cell;
        
        private WinCell mUIDisplayNetworkMaxCPCCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBNameWindow : WinWindow
    {
        
        public UITBNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBName";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBNameEdit
        {
            get
            {
                if ((this.mUITBNameEdit == null))
                {
                    this.mUITBNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBName";
                    this.mUITBNameEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUITBNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBMaximumCPMBidWindow : WinWindow
    {
        
        public UITBMaximumCPMBidWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBMaximumCPMBid";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBMaximumCPMBidEdit
        {
            get
            {
                if ((this.mUITBMaximumCPMBidEdit == null))
                {
                    this.mUITBMaximumCPMBidEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBMaximumCPMBidEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBMaximumCPMBid";
                    this.mUITBMaximumCPMBidEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUITBMaximumCPMBidEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBMaximumCPMBidEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow2 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow2()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UICBStatusWindow UICBStatusWindow
        {
            get
            {
                if ((this.mUICBStatusWindow == null))
                {
                    this.mUICBStatusWindow = new UICBStatusWindow(this);
                }
                return this.mUICBStatusWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICBStatusWindow mUICBStatusWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICBStatusWindow : WinWindow
    {
        
        public UICBStatusWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CBStatus";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICBStatusComboBox
        {
            get
            {
                if ((this.mUICBStatusComboBox == null))
                {
                    this.mUICBStatusComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICBStatusComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "CBStatus";
                    this.mUICBStatusComboBox.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUICBStatusComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICBStatusComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow3 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow3()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UITBMaximumCPCBidWindow UITBMaximumCPCBidWindow
        {
            get
            {
                if ((this.mUITBMaximumCPCBidWindow == null))
                {
                    this.mUITBMaximumCPCBidWindow = new UITBMaximumCPCBidWindow(this);
                }
                return this.mUITBMaximumCPCBidWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITBMaximumCPCBidWindow mUITBMaximumCPCBidWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBMaximumCPCBidWindow : WinWindow
    {
        
        public UITBMaximumCPCBidWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBMaximumCPCBid";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBMaximumCPCBidEdit
        {
            get
            {
                if ((this.mUITBMaximumCPCBidEdit == null))
                {
                    this.mUITBMaximumCPCBidEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBMaximumCPCBidEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBMaximumCPCBid";
                    this.mUITBMaximumCPCBidEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUITBMaximumCPCBidEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBMaximumCPCBidEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow4 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow4()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UITBMaximumCPCContentBWindow UITBMaximumCPCContentBWindow
        {
            get
            {
                if ((this.mUITBMaximumCPCContentBWindow == null))
                {
                    this.mUITBMaximumCPCContentBWindow = new UITBMaximumCPCContentBWindow(this);
                }
                return this.mUITBMaximumCPCContentBWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITBMaximumCPCContentBWindow mUITBMaximumCPCContentBWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBMaximumCPCContentBWindow : WinWindow
    {
        
        public UITBMaximumCPCContentBWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBMaximumCPCContentBid";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBMaximumCPCContentBEdit
        {
            get
            {
                if ((this.mUITBMaximumCPCContentBEdit == null))
                {
                    this.mUITBMaximumCPCContentBEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBMaximumCPCContentBEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBMaximumCPCContentBid";
                    this.mUITBMaximumCPCContentBEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUITBMaximumCPCContentBEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBMaximumCPCContentBEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow5 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow5()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UITBMaximumCPABidWindow UITBMaximumCPABidWindow
        {
            get
            {
                if ((this.mUITBMaximumCPABidWindow == null))
                {
                    this.mUITBMaximumCPABidWindow = new UITBMaximumCPABidWindow(this);
                }
                return this.mUITBMaximumCPABidWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITBMaximumCPABidWindow mUITBMaximumCPABidWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBMaximumCPABidWindow : WinWindow
    {
        
        public UITBMaximumCPABidWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBMaximumCPABid";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBMaximumCPABidEdit
        {
            get
            {
                if ((this.mUITBMaximumCPABidEdit == null))
                {
                    this.mUITBMaximumCPABidEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBMaximumCPABidEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBMaximumCPABid";
                    this.mUITBMaximumCPABidEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___qQ34N3 - adSage for Performance");
                    #endregion
                }
                return this.mUITBMaximumCPABidEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBMaximumCPABidEdit;
        #endregion
    }
}
