// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Google.UITestFramework.UIMaps.CampaignsClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public partial class Campaigns
    {
        
        /// <summary>
        /// ContextMenuDownloadAccount
        /// </summary>
        public void ContextMenuDownloadAccount()
        {
            #region Variable Declarations
            WinTreeItem uIWss_adsagetest163comTreeItem = this.UIWss_adsagetest163comWindow1.UIAccountTreeViewWindow.UIYourAccounts1TreeItem.UIWss_adsagetest163comTreeItem;
            WinMenuItem uIDownloadAccountMenuItem = this.UIItemWindow1.UIDropDownMenu.UIDownloadAccountMenuItem;
            #endregion

            // Right-Click 'Your Accounts(1)' -> 'wss_adsagetest@163.com(CNY)' tree item
            Mouse.Click(uIWss_adsagetest163comTreeItem, MouseButtons.Right, ModifierKeys.None, new Point(15, 10));

            // Click 'Download Account' menu item
            Mouse.Click(uIDownloadAccountMenuItem, new Point(82, 8));
        }
        
        /// <summary>
        /// ClickDeleteButton
        /// </summary>
        public void ClickDeleteButton()
        {
            #region Variable Declarations
            WinTabPage uICampaignsTabPage = this.UIWss_adsagetest163comWindow1.UIRibbonTabsTabList.UICampaignsTabPage;
            WinButton uIDeleteButton = this.UIWss_adsagetest163comWindow1.UIRibbonToolBar1.UIDeleteButton;
            #endregion

            // Click 'Campaigns' tab
            Mouse.Click(uICampaignsTabPage, new Point(32, 8));

            // Click 'Delete' button
            Mouse.Click(uIDeleteButton, new Point(6, 32));
        }
        
        /// <summary>
        /// ClickAddCPMCampaignButton
        /// </summary>
        public void ClickAddCPMCampaignButton()
        {
            #region Variable Declarations
            WinTabPage uICampaigns0TabPage = this.UIWss_adsagetest163comWindow1.UIItemTabList.UICampaigns0TabPage;
            WinMenuItem uIAddCampaignMenuItem = this.UIWss_adsagetest163comWindow1.UIRibbonToolBar2.UIAddCampaignMenuItem;
            WinButton uIAddCPMCampaignButton = this.UIItemWindow.UIItemList.UIAddCPMCampaignButton;
            #endregion

            // Click 'Campaigns(0)' tab
            Mouse.Click(uICampaigns0TabPage, new Point(60, 9));

            // Click 'Add Campaign' menu item
            Mouse.Click(uIAddCampaignMenuItem, new Point(37, 43));

            // Click 'Add CPM Campaign' button
            Mouse.Click(uIAddCPMCampaignButton, new Point(63, 12));
        }
        
        #region Properties
        public UIWss_adsagetest163comWindow UIWss_adsagetest163comWindow
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow == null))
                {
                    this.mUIWss_adsagetest163comWindow = new UIWss_adsagetest163comWindow();
                }
                return this.mUIWss_adsagetest163comWindow;
            }
        }
        
        public UIWss_adsagetest163comWindow1 UIWss_adsagetest163comWindow1
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow1 == null))
                {
                    this.mUIWss_adsagetest163comWindow1 = new UIWss_adsagetest163comWindow1();
                }
                return this.mUIWss_adsagetest163comWindow1;
            }
        }
        
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11();
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIWss_adsagetest163comWindow mUIWss_adsagetest163comWindow;
        
        private UIWss_adsagetest163comWindow1 mUIWss_adsagetest163comWindow1;
        
        private UIItemWindow2 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow : WinWindow
    {
        
        public UIWss_adsagetest163comWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "16";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIRow1Row UIRow1Row
        {
            get
            {
                if ((this.mUIRow1Row == null))
                {
                    this.mUIRow1Row = new UIRow1Row(this);
                }
                return this.mUIRow1Row;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIRow1Row mUIRow1Row;
        
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRow1Row : WinRow
    {
        
        public UIRow1Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "Row 1";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinCell UIServingCell
        {
            get
            {
                if ((this.mUIServingCell == null))
                {
                    this.mUIServingCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIServingCell.SearchProperties[WinCell.PropertyNames.Value] = "Serving";
                    this.mUIServingCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUIServingCell;
            }
        }
        
        public WinCell UILocalStatusExtensionCell
        {
            get
            {
                if ((this.mUILocalStatusExtensionCell == null))
                {
                    this.mUILocalStatusExtensionCell = new WinCell(this);
                    #region Search Criteria
                    this.mUILocalStatusExtensionCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUILocalStatusExtensionCell;
            }
        }
        
        public WinCell UILocalStateExtensionrCell
        {
            get
            {
                if ((this.mUILocalStateExtensionrCell == null))
                {
                    this.mUILocalStateExtensionrCell = new WinCell(this);
                    #region Search Criteria
                    this.mUILocalStateExtensionrCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUILocalStateExtensionrCell;
            }
        }
        
        public WinCell UICampaignAutoTestCell
        {
            get
            {
                if ((this.mUICampaignAutoTestCell == null))
                {
                    this.mUICampaignAutoTestCell = new WinCell(this);
                    #region Search Criteria
                    this.mUICampaignAutoTestCell.SearchProperties[WinCell.PropertyNames.Value] = "CampaignAutoTest";
                    this.mUICampaignAutoTestCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUICampaignAutoTestCell;
            }
        }
        
        public WinCell UIActiveCell
        {
            get
            {
                if ((this.mUIActiveCell == null))
                {
                    this.mUIActiveCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIActiveCell.SearchProperties[WinCell.PropertyNames.Value] = "Active";
                    this.mUIActiveCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUIActiveCell;
            }
        }
        
        public WinCell UIItem1000Cell
        {
            get
            {
                if ((this.mUIItem1000Cell == null))
                {
                    this.mUIItem1000Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem1000Cell.SearchProperties[WinCell.PropertyNames.Value] = "10.00";
                    this.mUIItem1000Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUIItem1000Cell;
            }
        }
        
        public WinCell UIItem9192011Cell
        {
            get
            {
                if ((this.mUIItem9192011Cell == null))
                {
                    this.mUIItem9192011Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem9192011Cell.SearchProperties[WinCell.PropertyNames.Value] = "9/19/2011";
                    this.mUIItem9192011Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUIItem9192011Cell;
            }
        }
        
        public WinCell UIItem09192012Cell
        {
            get
            {
                if ((this.mUIItem09192012Cell == null))
                {
                    this.mUIItem09192012Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem09192012Cell.SearchProperties[WinCell.PropertyNames.Value] = "09/19/2012";
                    this.mUIItem09192012Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUIItem09192012Cell;
            }
        }
        
        public WinCell UINoneCell
        {
            get
            {
                if ((this.mUINoneCell == null))
                {
                    this.mUINoneCell = new WinCell(this);
                    #region Search Criteria
                    this.mUINoneCell.SearchProperties[WinCell.PropertyNames.Value] = "None";
                    this.mUINoneCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUINoneCell;
            }
        }
        
        public WinCell UIRelevantpagesacrosstCell
        {
            get
            {
                if ((this.mUIRelevantpagesacrosstCell == null))
                {
                    this.mUIRelevantpagesacrosstCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIRelevantpagesacrosstCell.SearchProperties[WinCell.PropertyNames.Value] = "Relevant pages across the entire network";
                    this.mUIRelevantpagesacrosstCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUIRelevantpagesacrosstCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIServingCell;
        
        private WinCell mUILocalStatusExtensionCell;
        
        private WinCell mUILocalStateExtensionrCell;
        
        private WinCell mUICampaignAutoTestCell;
        
        private WinCell mUIActiveCell;
        
        private WinCell mUIItem1000Cell;
        
        private WinCell mUIItem9192011Cell;
        
        private WinCell mUIItem09192012Cell;
        
        private WinCell mUINoneCell;
        
        private WinCell mUIRelevantpagesacrosstCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemTable : WinTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIHeaderPanelClient UIHeaderPanelClient
        {
            get
            {
                if ((this.mUIHeaderPanelClient == null))
                {
                    this.mUIHeaderPanelClient = new UIHeaderPanelClient(this);
                }
                return this.mUIHeaderPanelClient;
            }
        }
        
        public UIDataPanelClient UIDataPanelClient
        {
            get
            {
                if ((this.mUIDataPanelClient == null))
                {
                    this.mUIDataPanelClient = new UIDataPanelClient(this);
                }
                return this.mUIDataPanelClient;
            }
        }
        #endregion
        
        #region Fields
        private UIHeaderPanelClient mUIHeaderPanelClient;
        
        private UIDataPanelClient mUIDataPanelClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIHeaderPanelClient : WinClient
    {
        
        public UIHeaderPanelClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinRowHeader UIItemRowHeader
        {
            get
            {
                if ((this.mUIItemRowHeader == null))
                {
                    this.mUIItemRowHeader = new WinRowHeader(this);
                    #region Search Criteria
                    this.mUIItemRowHeader.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUIItemRowHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinRowHeader mUIItemRowHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDataPanelClient : WinClient
    {
        
        public UIDataPanelClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Data Panel";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinRow UINewItemRowRow
        {
            get
            {
                if ((this.mUINewItemRowRow == null))
                {
                    this.mUINewItemRowRow = new WinRow(this);
                    #region Search Criteria
                    this.mUINewItemRowRow.SearchProperties[WinRow.PropertyNames.Name] = "NewItem Row";
                    this.mUINewItemRowRow.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mUINewItemRowRow.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUINewItemRowRow;
            }
        }
        
        public WinRow UIRow1Row
        {
            get
            {
                if ((this.mUIRow1Row == null))
                {
                    this.mUIRow1Row = new WinRow(this);
                    #region Search Criteria
                    this.mUIRow1Row.SearchProperties[WinRow.PropertyNames.Name] = "Row 1";
                    this.mUIRow1Row.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mUIRow1Row.WindowTitles.Add("wss_adsagetest@163.com(CNY) - CampaignAutoTest - adSage for Performance");
                    #endregion
                }
                return this.mUIRow1Row;
            }
        }
        #endregion
        
        #region Fields
        private WinRow mUINewItemRowRow;
        
        private WinRow mUIRow1Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow1 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UITBNameWindow UITBNameWindow
        {
            get
            {
                if ((this.mUITBNameWindow == null))
                {
                    this.mUITBNameWindow = new UITBNameWindow(this);
                }
                return this.mUITBNameWindow;
            }
        }
        
        public UITBDailyBudgetWindow UITBDailyBudgetWindow
        {
            get
            {
                if ((this.mUITBDailyBudgetWindow == null))
                {
                    this.mUITBDailyBudgetWindow = new UITBDailyBudgetWindow(this);
                }
                return this.mUITBDailyBudgetWindow;
            }
        }
        
        public UICBStatusWindow UICBStatusWindow
        {
            get
            {
                if ((this.mUICBStatusWindow == null))
                {
                    this.mUICBStatusWindow = new UICBStatusWindow(this);
                }
                return this.mUICBStatusWindow;
            }
        }
        
        public UICBSearchNetworkWindow UICBSearchNetworkWindow
        {
            get
            {
                if ((this.mUICBSearchNetworkWindow == null))
                {
                    this.mUICBSearchNetworkWindow = new UICBSearchNetworkWindow(this);
                }
                return this.mUICBSearchNetworkWindow;
            }
        }
        
        public UIDTPStartDateWindow UIDTPStartDateWindow
        {
            get
            {
                if ((this.mUIDTPStartDateWindow == null))
                {
                    this.mUIDTPStartDateWindow = new UIDTPStartDateWindow(this);
                }
                return this.mUIDTPStartDateWindow;
            }
        }
        
        public UIDTPEndDateWindow UIDTPEndDateWindow
        {
            get
            {
                if ((this.mUIDTPEndDateWindow == null))
                {
                    this.mUIDTPEndDateWindow = new UIDTPEndDateWindow(this);
                }
                return this.mUIDTPEndDateWindow;
            }
        }
        
        public UICBContentNetworkWindow UICBContentNetworkWindow
        {
            get
            {
                if ((this.mUICBContentNetworkWindow == null))
                {
                    this.mUICBContentNetworkWindow = new UICBContentNetworkWindow(this);
                }
                return this.mUICBContentNetworkWindow;
            }
        }
        
        public UIRibbonTabsTabList UIRibbonTabsTabList
        {
            get
            {
                if ((this.mUIRibbonTabsTabList == null))
                {
                    this.mUIRibbonTabsTabList = new UIRibbonTabsTabList(this);
                }
                return this.mUIRibbonTabsTabList;
            }
        }
        
        public UIRibbonToolBar UIRibbonToolBar
        {
            get
            {
                if ((this.mUIRibbonToolBar == null))
                {
                    this.mUIRibbonToolBar = new UIRibbonToolBar(this);
                }
                return this.mUIRibbonToolBar;
            }
        }
        
        public UIAccountTreeViewWindow UIAccountTreeViewWindow
        {
            get
            {
                if ((this.mUIAccountTreeViewWindow == null))
                {
                    this.mUIAccountTreeViewWindow = new UIAccountTreeViewWindow(this);
                }
                return this.mUIAccountTreeViewWindow;
            }
        }
        
        public UIRibbonToolBar1 UIRibbonToolBar1
        {
            get
            {
                if ((this.mUIRibbonToolBar1 == null))
                {
                    this.mUIRibbonToolBar1 = new UIRibbonToolBar1(this);
                }
                return this.mUIRibbonToolBar1;
            }
        }
        
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        
        public UIRibbonToolBar2 UIRibbonToolBar2
        {
            get
            {
                if ((this.mUIRibbonToolBar2 == null))
                {
                    this.mUIRibbonToolBar2 = new UIRibbonToolBar2(this);
                }
                return this.mUIRibbonToolBar2;
            }
        }
        #endregion
        
        #region Fields
        private UITBNameWindow mUITBNameWindow;
        
        private UITBDailyBudgetWindow mUITBDailyBudgetWindow;
        
        private UICBStatusWindow mUICBStatusWindow;
        
        private UICBSearchNetworkWindow mUICBSearchNetworkWindow;
        
        private UIDTPStartDateWindow mUIDTPStartDateWindow;
        
        private UIDTPEndDateWindow mUIDTPEndDateWindow;
        
        private UICBContentNetworkWindow mUICBContentNetworkWindow;
        
        private UIRibbonTabsTabList mUIRibbonTabsTabList;
        
        private UIRibbonToolBar mUIRibbonToolBar;
        
        private UIAccountTreeViewWindow mUIAccountTreeViewWindow;
        
        private UIRibbonToolBar1 mUIRibbonToolBar1;
        
        private UIItemTabList mUIItemTabList;
        
        private UIRibbonToolBar2 mUIRibbonToolBar2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBNameWindow : WinWindow
    {
        
        public UITBNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBName";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBNameEdit
        {
            get
            {
                if ((this.mUITBNameEdit == null))
                {
                    this.mUITBNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBName";
                    this.mUITBNameEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUITBNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBDailyBudgetWindow : WinWindow
    {
        
        public UITBDailyBudgetWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBDailyBudget";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBDailyBudgetEdit
        {
            get
            {
                if ((this.mUITBDailyBudgetEdit == null))
                {
                    this.mUITBDailyBudgetEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBDailyBudgetEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBDailyBudget";
                    this.mUITBDailyBudgetEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUITBDailyBudgetEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBDailyBudgetEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICBStatusWindow : WinWindow
    {
        
        public UICBStatusWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CBStatus";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICBStatusComboBox
        {
            get
            {
                if ((this.mUICBStatusComboBox == null))
                {
                    this.mUICBStatusComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICBStatusComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "CBStatus";
                    this.mUICBStatusComboBox.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUICBStatusComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICBStatusComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICBSearchNetworkWindow : WinWindow
    {
        
        public UICBSearchNetworkWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CBSearchNetwork";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICBSearchNetworkComboBox
        {
            get
            {
                if ((this.mUICBSearchNetworkComboBox == null))
                {
                    this.mUICBSearchNetworkComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICBSearchNetworkComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "CBSearchNetwork";
                    this.mUICBSearchNetworkComboBox.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUICBSearchNetworkComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICBSearchNetworkComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDTPStartDateWindow : WinWindow
    {
        
        public UIDTPStartDateWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "DTPStartDate";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIDTPStartDateClient UIDTPStartDateClient
        {
            get
            {
                if ((this.mUIDTPStartDateClient == null))
                {
                    this.mUIDTPStartDateClient = new UIDTPStartDateClient(this);
                }
                return this.mUIDTPStartDateClient;
            }
        }
        
        public UITuesdaySeptember2020DropDown UITuesdaySeptember2020DropDown
        {
            get
            {
                if ((this.mUITuesdaySeptember2020DropDown == null))
                {
                    this.mUITuesdaySeptember2020DropDown = new UITuesdaySeptember2020DropDown(this);
                }
                return this.mUITuesdaySeptember2020DropDown;
            }
        }
        #endregion
        
        #region Fields
        private UIDTPStartDateClient mUIDTPStartDateClient;
        
        private UITuesdaySeptember2020DropDown mUITuesdaySeptember2020DropDown;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDTPStartDateClient : WinClient
    {
        
        public UIDTPStartDateClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "DTPStartDate";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinControl UIMondaySeptember19201DropDown
        {
            get
            {
                if ((this.mUIMondaySeptember19201DropDown == null))
                {
                    this.mUIMondaySeptember19201DropDown = new WinControl(this);
                    #region Search Criteria
                    this.mUIMondaySeptember19201DropDown.SearchProperties[UITestControl.PropertyNames.Name] = "Monday, September 19, 2011";
                    this.mUIMondaySeptember19201DropDown.SearchProperties[UITestControl.PropertyNames.ControlType] = "DropDown";
                    this.mUIMondaySeptember19201DropDown.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIMondaySeptember19201DropDown;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIMondaySeptember19201DropDown;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITuesdaySeptember2020DropDown : WinControl
    {
        
        public UITuesdaySeptember2020DropDown(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Tuesday, September 20, 2011";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "DropDown";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinControl UITuesdaySeptember2020DropDown1
        {
            get
            {
                if ((this.mUITuesdaySeptember2020DropDown1 == null))
                {
                    this.mUITuesdaySeptember2020DropDown1 = new WinControl(this);
                    #region Search Criteria
                    this.mUITuesdaySeptember2020DropDown1.SearchProperties[UITestControl.PropertyNames.Name] = "Tuesday, September 20, 2011";
                    this.mUITuesdaySeptember2020DropDown1.SearchProperties[UITestControl.PropertyNames.ControlType] = "DropDown";
                    this.mUITuesdaySeptember2020DropDown1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUITuesdaySeptember2020DropDown1.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUITuesdaySeptember2020DropDown1;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUITuesdaySeptember2020DropDown1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDTPEndDateWindow : WinWindow
    {
        
        public UIDTPEndDateWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "DTPEndDate";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIWednesdaySeptember19DropDown UIWednesdaySeptember19DropDown
        {
            get
            {
                if ((this.mUIWednesdaySeptember19DropDown == null))
                {
                    this.mUIWednesdaySeptember19DropDown = new UIWednesdaySeptember19DropDown(this);
                }
                return this.mUIWednesdaySeptember19DropDown;
            }
        }
        
        public WinClient UIDTPEndDateClient
        {
            get
            {
                if ((this.mUIDTPEndDateClient == null))
                {
                    this.mUIDTPEndDateClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIDTPEndDateClient.SearchProperties[WinControl.PropertyNames.Name] = "DTPEndDate";
                    this.mUIDTPEndDateClient.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIDTPEndDateClient;
            }
        }
        #endregion
        
        #region Fields
        private UIWednesdaySeptember19DropDown mUIWednesdaySeptember19DropDown;
        
        private WinClient mUIDTPEndDateClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWednesdaySeptember19DropDown : WinControl
    {
        
        public UIWednesdaySeptember19DropDown(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Wednesday, September 19, 2012";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "DropDown";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinControl UIWednesdaySeptember19DropDown1
        {
            get
            {
                if ((this.mUIWednesdaySeptember19DropDown1 == null))
                {
                    this.mUIWednesdaySeptember19DropDown1 = new WinControl(this);
                    #region Search Criteria
                    this.mUIWednesdaySeptember19DropDown1.SearchProperties[UITestControl.PropertyNames.Name] = "Wednesday, September 19, 2012";
                    this.mUIWednesdaySeptember19DropDown1.SearchProperties[UITestControl.PropertyNames.ControlType] = "DropDown";
                    this.mUIWednesdaySeptember19DropDown1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIWednesdaySeptember19DropDown1.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIWednesdaySeptember19DropDown1;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIWednesdaySeptember19DropDown1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICBContentNetworkWindow : WinWindow
    {
        
        public UICBContentNetworkWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CBContentNetwork";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICBContentNetworkComboBox
        {
            get
            {
                if ((this.mUICBContentNetworkComboBox == null))
                {
                    this.mUICBContentNetworkComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICBContentNetworkComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "CBContentNetwork";
                    this.mUICBContentNetworkComboBox.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUICBContentNetworkComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICBContentNetworkComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonTabsTabList : WinTabList
    {
        
        public UIRibbonTabsTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTabList.PropertyNames.Name] = "Ribbon Tabs";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinTabPage UIHomeTabPage
        {
            get
            {
                if ((this.mUIHomeTabPage == null))
                {
                    this.mUIHomeTabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUIHomeTabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Home";
                    this.mUIHomeTabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIHomeTabPage;
            }
        }
        
        public WinTabPage UICampaignsTabPage
        {
            get
            {
                if ((this.mUICampaignsTabPage == null))
                {
                    this.mUICampaignsTabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUICampaignsTabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Campaigns";
                    this.mUICampaignsTabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUICampaignsTabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUIHomeTabPage;
        
        private WinTabPage mUICampaignsTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonToolBar : WinToolBar
    {
        
        public UIRibbonToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Synchronization";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinButton UIUploadAccountsButton
        {
            get
            {
                if ((this.mUIUploadAccountsButton == null))
                {
                    this.mUIUploadAccountsButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIUploadAccountsButton.SearchProperties[WinButton.PropertyNames.Name] = "Upload Accounts";
                    this.mUIUploadAccountsButton.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIUploadAccountsButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIUploadAccountsButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIAccountTreeViewWindow : WinWindow
    {
        
        public UIAccountTreeViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "accountTreeView";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIYourAccounts1TreeItem UIYourAccounts1TreeItem
        {
            get
            {
                if ((this.mUIYourAccounts1TreeItem == null))
                {
                    this.mUIYourAccounts1TreeItem = new UIYourAccounts1TreeItem(this);
                }
                return this.mUIYourAccounts1TreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIYourAccounts1TreeItem mUIYourAccounts1TreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIYourAccounts1TreeItem : WinTreeItem
    {
        
        public UIYourAccounts1TreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Your Accounts(1)";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UIWss_adsagetest163comTreeItem
        {
            get
            {
                if ((this.mUIWss_adsagetest163comTreeItem == null))
                {
                    this.mUIWss_adsagetest163comTreeItem = new WinTreeItem(this);
                    #region Search Criteria
                    this.mUIWss_adsagetest163comTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "wss_adsagetest@163.com(CNY)";
                    this.mUIWss_adsagetest163comTreeItem.SearchProperties["Value"] = "1";
                    this.mUIWss_adsagetest163comTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIWss_adsagetest163comTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIWss_adsagetest163comTreeItem.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIWss_adsagetest163comTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUIWss_adsagetest163comTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonToolBar1 : WinToolBar
    {
        
        public UIRibbonToolBar1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Delete";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDeleteButton.SearchProperties[WinButton.PropertyNames.Name] = "Delete";
                    this.mUIDeleteButton.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIDeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemTabList : WinTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinTabPage UICampaigns0TabPage
        {
            get
            {
                if ((this.mUICampaigns0TabPage == null))
                {
                    this.mUICampaigns0TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUICampaigns0TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Campaigns(0)";
                    this.mUICampaigns0TabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUICampaigns0TabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUICampaigns0TabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonToolBar2 : WinToolBar
    {
        
        public UIRibbonToolBar2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "AddCampaign";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAddCampaignMenuItem
        {
            get
            {
                if ((this.mUIAddCampaignMenuItem == null))
                {
                    this.mUIAddCampaignMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAddCampaignMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Add Campaign";
                    this.mUIAddCampaignMenuItem.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIAddCampaignMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAddCampaignMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        
        private UIItemList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            #endregion
        }
        
        #region Properties
        public WinClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new WinClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemList : WinList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinButton UIAddCPMCampaignButton
        {
            get
            {
                if ((this.mUIAddCPMCampaignButton == null))
                {
                    this.mUIAddCPMCampaignButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIAddCPMCampaignButton.SearchProperties[WinButton.PropertyNames.Name] = "Add CPM Campaign";
                    #endregion
                }
                return this.mUIAddCPMCampaignButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIAddCPMCampaignButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "DropDown";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            #endregion
        }
        
        #region Properties
        public UIDropDownMenu UIDropDownMenu
        {
            get
            {
                if ((this.mUIDropDownMenu == null))
                {
                    this.mUIDropDownMenu = new UIDropDownMenu(this);
                }
                return this.mUIDropDownMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIDropDownMenu mUIDropDownMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDropDownMenu : WinMenu
    {
        
        public UIDropDownMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "DropDown";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIDownloadAccountMenuItem
        {
            get
            {
                if ((this.mUIDownloadAccountMenuItem == null))
                {
                    this.mUIDownloadAccountMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIDownloadAccountMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Download Account";
                    #endregion
                }
                return this.mUIDownloadAccountMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIDownloadAccountMenuItem;
        #endregion
    }
}
