// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Google.UITestFramework.UIMaps.TextAdClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public partial class TextAd
    {
        
        /// <summary>
        /// ClickAddTextAdButton
        /// </summary>
        public void ClickAddTextAdButton()
        {
            #region Variable Declarations
            WinTabPage uITextAds0TabPage = this.UIWss_adsagetest163comWindow1.UIItemTabList.UITextAds0TabPage;
            WinButton uIAddTextAdButton = this.UIWss_adsagetest163comWindow1.UIRibbonToolBar.UIAddTextAdButton;
            WinButton uIOKButton = this.UIChoosetheAdGroupWindow.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Text Ads(0)' tab
            Mouse.Click(uITextAds0TabPage, new Point(36, 8));

            // Click 'Add Text Ad' button
            Mouse.Click(uIAddTextAdButton, new Point(23, 24));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(44, 4));
        }
        
        /// <summary>
        /// ClickAdGoup1Tab
        /// </summary>
        public void ClickAdGoup1Tab()
        {
            #region Variable Declarations
            WinTabPage uIAdGroups1TabPage = this.UIWss_adsagetest163comWindow1.UIItemTabList.UIAdGroups1TabPage;
            #endregion

            // Click 'Ad Groups(1)' tab
            Mouse.Click(uIAdGroups1TabPage, new Point(39, 2));
        }
        
        /// <summary>
        /// ClickDeleteTextAdButton
        /// </summary>
        public void ClickDeleteTextAdButton()
        {
            #region Variable Declarations
            WinTabPage uITextAdsTabPage = this.UIWss_adsagetest163comWindow1.UIRibbonTabsTabList.UITextAdsTabPage;
            WinButton uIDeleteButton = this.UIWss_adsagetest163comWindow1.UIRibbonToolBar1.UIDeleteButton;
            #endregion

            // Click 'Text Ads' tab
            Mouse.Click(uITextAdsTabPage, new Point(28, 6));

            // Click 'Delete' button
            Mouse.Click(uIDeleteButton, new Point(14, 33));
        }
        
        /// <summary>
        /// ClickCampaign1Tab
        /// </summary>
        public void ClickCampaign1Tab()
        {
            #region Variable Declarations
            WinTabPage uICampaigns1TabPage = this.UIWss_adsagetest163comWindow1.UIItemTabList.UICampaigns1TabPage;
            #endregion

            // Click 'Campaigns(1)' tab
            Mouse.Click(uICampaigns1TabPage, new Point(25, 7));
        }
        
        #region Properties
        public UIWss_adsagetest163comWindow UIWss_adsagetest163comWindow
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow == null))
                {
                    this.mUIWss_adsagetest163comWindow = new UIWss_adsagetest163comWindow();
                }
                return this.mUIWss_adsagetest163comWindow;
            }
        }
        
        public UIChoosetheAdGroupWindow UIChoosetheAdGroupWindow
        {
            get
            {
                if ((this.mUIChoosetheAdGroupWindow == null))
                {
                    this.mUIChoosetheAdGroupWindow = new UIChoosetheAdGroupWindow();
                }
                return this.mUIChoosetheAdGroupWindow;
            }
        }
        
        public UIWss_adsagetest163comWindow1 UIWss_adsagetest163comWindow1
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow1 == null))
                {
                    this.mUIWss_adsagetest163comWindow1 = new UIWss_adsagetest163comWindow1();
                }
                return this.mUIWss_adsagetest163comWindow1;
            }
        }
        
        public UIWss_adsagetest163comWindow2 UIWss_adsagetest163comWindow2
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow2 == null))
                {
                    this.mUIWss_adsagetest163comWindow2 = new UIWss_adsagetest163comWindow2();
                }
                return this.mUIWss_adsagetest163comWindow2;
            }
        }
        
        public UIWss_adsagetest163comWindow3 UIWss_adsagetest163comWindow3
        {
            get
            {
                if ((this.mUIWss_adsagetest163comWindow3 == null))
                {
                    this.mUIWss_adsagetest163comWindow3 = new UIWss_adsagetest163comWindow3();
                }
                return this.mUIWss_adsagetest163comWindow3;
            }
        }
        #endregion
        
        #region Fields
        private UIWss_adsagetest163comWindow mUIWss_adsagetest163comWindow;
        
        private UIChoosetheAdGroupWindow mUIChoosetheAdGroupWindow;
        
        private UIWss_adsagetest163comWindow1 mUIWss_adsagetest163comWindow1;
        
        private UIWss_adsagetest163comWindow2 mUIWss_adsagetest163comWindow2;
        
        private UIWss_adsagetest163comWindow3 mUIWss_adsagetest163comWindow3;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow : WinWindow
    {
        
        public UIWss_adsagetest163comWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UITBHeadlineWindow UITBHeadlineWindow
        {
            get
            {
                if ((this.mUITBHeadlineWindow == null))
                {
                    this.mUITBHeadlineWindow = new UITBHeadlineWindow(this);
                }
                return this.mUITBHeadlineWindow;
            }
        }
        
        public UITBDesc1Window UITBDesc1Window
        {
            get
            {
                if ((this.mUITBDesc1Window == null))
                {
                    this.mUITBDesc1Window = new UITBDesc1Window(this);
                }
                return this.mUITBDesc1Window;
            }
        }
        
        public UITBDesc2Window UITBDesc2Window
        {
            get
            {
                if ((this.mUITBDesc2Window == null))
                {
                    this.mUITBDesc2Window = new UITBDesc2Window(this);
                }
                return this.mUITBDesc2Window;
            }
        }
        
        public UITBDisplayWindow UITBDisplayWindow
        {
            get
            {
                if ((this.mUITBDisplayWindow == null))
                {
                    this.mUITBDisplayWindow = new UITBDisplayWindow(this);
                }
                return this.mUITBDisplayWindow;
            }
        }
        
        public UIGoogleTextAdEditorWindow UIGoogleTextAdEditorWindow
        {
            get
            {
                if ((this.mUIGoogleTextAdEditorWindow == null))
                {
                    this.mUIGoogleTextAdEditorWindow = new UIGoogleTextAdEditorWindow(this);
                }
                return this.mUIGoogleTextAdEditorWindow;
            }
        }
        
        public UICBStatusWindow UICBStatusWindow
        {
            get
            {
                if ((this.mUICBStatusWindow == null))
                {
                    this.mUICBStatusWindow = new UICBStatusWindow(this);
                }
                return this.mUICBStatusWindow;
            }
        }
        
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        
        public UIRibbonToolBar UIRibbonToolBar
        {
            get
            {
                if ((this.mUIRibbonToolBar == null))
                {
                    this.mUIRibbonToolBar = new UIRibbonToolBar(this);
                }
                return this.mUIRibbonToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UITBHeadlineWindow mUITBHeadlineWindow;
        
        private UITBDesc1Window mUITBDesc1Window;
        
        private UITBDesc2Window mUITBDesc2Window;
        
        private UITBDisplayWindow mUITBDisplayWindow;
        
        private UIGoogleTextAdEditorWindow mUIGoogleTextAdEditorWindow;
        
        private UICBStatusWindow mUICBStatusWindow;
        
        private UIItemTabList mUIItemTabList;
        
        private UIRibbonToolBar mUIRibbonToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBHeadlineWindow : WinWindow
    {
        
        public UITBHeadlineWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBHeadline";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBHeadlineEdit
        {
            get
            {
                if ((this.mUITBHeadlineEdit == null))
                {
                    this.mUITBHeadlineEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBHeadlineEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBHeadline";
                    this.mUITBHeadlineEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
                    #endregion
                }
                return this.mUITBHeadlineEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBHeadlineEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBDesc1Window : WinWindow
    {
        
        public UITBDesc1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBDesc1";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBDesc1Edit
        {
            get
            {
                if ((this.mUITBDesc1Edit == null))
                {
                    this.mUITBDesc1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBDesc1Edit.SearchProperties[WinEdit.PropertyNames.Name] = "TBDesc1";
                    this.mUITBDesc1Edit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
                    #endregion
                }
                return this.mUITBDesc1Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBDesc1Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBDesc2Window : WinWindow
    {
        
        public UITBDesc2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBDesc2";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBDesc2Edit
        {
            get
            {
                if ((this.mUITBDesc2Edit == null))
                {
                    this.mUITBDesc2Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBDesc2Edit.SearchProperties[WinEdit.PropertyNames.Name] = "TBDesc2";
                    this.mUITBDesc2Edit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
                    #endregion
                }
                return this.mUITBDesc2Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBDesc2Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBDisplayWindow : WinWindow
    {
        
        public UITBDisplayWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBDisplay";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBDisplayEdit
        {
            get
            {
                if ((this.mUITBDisplayEdit == null))
                {
                    this.mUITBDisplayEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBDisplayEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBDisplay";
                    this.mUITBDisplayEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
                    #endregion
                }
                return this.mUITBDisplayEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBDisplayEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIGoogleTextAdEditorWindow : WinWindow
    {
        
        public UIGoogleTextAdEditorWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "GoogleTextAdEditor";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIGoogleTextAdEditorClient UIGoogleTextAdEditorClient
        {
            get
            {
                if ((this.mUIGoogleTextAdEditorClient == null))
                {
                    this.mUIGoogleTextAdEditorClient = new UIGoogleTextAdEditorClient(this);
                }
                return this.mUIGoogleTextAdEditorClient;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleTextAdEditorClient mUIGoogleTextAdEditorClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIGoogleTextAdEditorClient : WinClient
    {
        
        public UIGoogleTextAdEditorClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "GoogleTextAdEditor";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAppendtextEdit
        {
            get
            {
                if ((this.mUIAppendtextEdit == null))
                {
                    this.mUIAppendtextEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAppendtextEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Append text";
                    this.mUIAppendtextEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
                    #endregion
                }
                return this.mUIAppendtextEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAppendtextEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICBStatusWindow : WinWindow
    {
        
        public UICBStatusWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CBStatus";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICBStatusComboBox
        {
            get
            {
                if ((this.mUICBStatusComboBox == null))
                {
                    this.mUICBStatusComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICBStatusComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "CBStatus";
                    this.mUICBStatusComboBox.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
                    #endregion
                }
                return this.mUICBStatusComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICBStatusComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemTabList : WinTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinTabPage UITextAds0TabPage
        {
            get
            {
                if ((this.mUITextAds0TabPage == null))
                {
                    this.mUITextAds0TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUITextAds0TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Text Ads(0)";
                    this.mUITextAds0TabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
                    #endregion
                }
                return this.mUITextAds0TabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUITextAds0TabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonToolBar : WinToolBar
    {
        
        public UIRibbonToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "New";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinButton UIAddTextAdButton
        {
            get
            {
                if ((this.mUIAddTextAdButton == null))
                {
                    this.mUIAddTextAdButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIAddTextAdButton.SearchProperties[WinButton.PropertyNames.Name] = "Add Text Ad";
                    this.mUIAddTextAdButton.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___iLQ5VX - ___-453uW - adSage for Performance");
                    #endregion
                }
                return this.mUIAddTextAdButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIAddTextAdButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIChoosetheAdGroupWindow : WinWindow
    {
        
        public UIChoosetheAdGroupWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Choose the Ad Group";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Choose the Ad Group");
            #endregion
        }
        
        #region Properties
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "BTOK";
            this.WindowTitles.Add("Choose the Ad Group");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Choose the Ad Group");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow1 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIItemTabList1 UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList1(this);
                }
                return this.mUIItemTabList;
            }
        }
        
        public UIRibbonToolBar1 UIRibbonToolBar
        {
            get
            {
                if ((this.mUIRibbonToolBar == null))
                {
                    this.mUIRibbonToolBar = new UIRibbonToolBar1(this);
                }
                return this.mUIRibbonToolBar;
            }
        }
        
        public UIRibbonToolBar11 UIRibbonToolBar1
        {
            get
            {
                if ((this.mUIRibbonToolBar1 == null))
                {
                    this.mUIRibbonToolBar1 = new UIRibbonToolBar11(this);
                }
                return this.mUIRibbonToolBar1;
            }
        }
        
        public UIRibbonTabsTabList UIRibbonTabsTabList
        {
            get
            {
                if ((this.mUIRibbonTabsTabList == null))
                {
                    this.mUIRibbonTabsTabList = new UIRibbonTabsTabList(this);
                }
                return this.mUIRibbonTabsTabList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTabList1 mUIItemTabList;
        
        private UIRibbonToolBar1 mUIRibbonToolBar;
        
        private UIRibbonToolBar11 mUIRibbonToolBar1;
        
        private UIRibbonTabsTabList mUIRibbonTabsTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemTabList1 : WinTabList
    {
        
        public UIItemTabList1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinTabPage UITextAds0TabPage
        {
            get
            {
                if ((this.mUITextAds0TabPage == null))
                {
                    this.mUITextAds0TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUITextAds0TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Text Ads(0)";
                    this.mUITextAds0TabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUITextAds0TabPage;
            }
        }
        
        public WinTabPage UIAdGroups1TabPage
        {
            get
            {
                if ((this.mUIAdGroups1TabPage == null))
                {
                    this.mUIAdGroups1TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUIAdGroups1TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Ad Groups(1)";
                    this.mUIAdGroups1TabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIAdGroups1TabPage;
            }
        }
        
        public WinTabPage UICampaigns1TabPage
        {
            get
            {
                if ((this.mUICampaigns1TabPage == null))
                {
                    this.mUICampaigns1TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUICampaigns1TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Campaigns(1)";
                    this.mUICampaigns1TabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUICampaigns1TabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUITextAds0TabPage;
        
        private WinTabPage mUIAdGroups1TabPage;
        
        private WinTabPage mUICampaigns1TabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonToolBar1 : WinToolBar
    {
        
        public UIRibbonToolBar1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "New";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinButton UIAddTextAdButton
        {
            get
            {
                if ((this.mUIAddTextAdButton == null))
                {
                    this.mUIAddTextAdButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIAddTextAdButton.SearchProperties[WinButton.PropertyNames.Name] = "Add Text Ad";
                    this.mUIAddTextAdButton.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIAddTextAdButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIAddTextAdButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonToolBar11 : WinToolBar
    {
        
        public UIRibbonToolBar11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Delete";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDeleteButton.SearchProperties[WinButton.PropertyNames.Name] = "Delete";
                    this.mUIDeleteButton.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUIDeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRibbonTabsTabList : WinTabList
    {
        
        public UIRibbonTabsTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTabList.PropertyNames.Name] = "Ribbon Tabs";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinTabPage UITextAdsTabPage
        {
            get
            {
                if ((this.mUITextAdsTabPage == null))
                {
                    this.mUITextAdsTabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUITextAdsTabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Text Ads";
                    this.mUITextAdsTabPage.WindowTitles.Add("wss_adsagetest@163.com(CNY) - adSage for Performance");
                    #endregion
                }
                return this.mUITextAdsTabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUITextAdsTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow2 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow2()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIHeadlineWindow UIHeadlineWindow
        {
            get
            {
                if ((this.mUIHeadlineWindow == null))
                {
                    this.mUIHeadlineWindow = new UIHeadlineWindow(this);
                }
                return this.mUIHeadlineWindow;
            }
        }
        
        public UIDescriptionLine1Window UIDescriptionLine1Window
        {
            get
            {
                if ((this.mUIDescriptionLine1Window == null))
                {
                    this.mUIDescriptionLine1Window = new UIDescriptionLine1Window(this);
                }
                return this.mUIDescriptionLine1Window;
            }
        }
        
        public UIDescriptionLine2Window UIDescriptionLine2Window
        {
            get
            {
                if ((this.mUIDescriptionLine2Window == null))
                {
                    this.mUIDescriptionLine2Window = new UIDescriptionLine2Window(this);
                }
                return this.mUIDescriptionLine2Window;
            }
        }
        
        public UIDisplayURLWindow UIDisplayURLWindow
        {
            get
            {
                if ((this.mUIDisplayURLWindow == null))
                {
                    this.mUIDisplayURLWindow = new UIDisplayURLWindow(this);
                }
                return this.mUIDisplayURLWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHeadlineWindow mUIHeadlineWindow;
        
        private UIDescriptionLine1Window mUIDescriptionLine1Window;
        
        private UIDescriptionLine2Window mUIDescriptionLine2Window;
        
        private UIDisplayURLWindow mUIDisplayURLWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIHeadlineWindow : WinWindow
    {
        
        public UIHeadlineWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "LLBHeadline";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIHeadlineText UIHeadlineText
        {
            get
            {
                if ((this.mUIHeadlineText == null))
                {
                    this.mUIHeadlineText = new UIHeadlineText(this);
                }
                return this.mUIHeadlineText;
            }
        }
        #endregion
        
        #region Fields
        private UIHeadlineText mUIHeadlineText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIHeadlineText : WinText
    {
        
        public UIHeadlineText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinText.PropertyNames.Name] = "LLBHeadline";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinHyperlink UIHeadlineHyperlink
        {
            get
            {
                if ((this.mUIHeadlineHyperlink == null))
                {
                    this.mUIHeadlineHyperlink = new WinHyperlink(this);
                    #region Search Criteria
                    this.mUIHeadlineHyperlink.SearchProperties[WinHyperlink.PropertyNames.ControlName] = "LLBHeadline";
                    this.mUIHeadlineHyperlink.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
                    #endregion
                }
                return this.mUIHeadlineHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WinHyperlink mUIHeadlineHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDescriptionLine1Window : WinWindow
    {
        
        public UIDescriptionLine1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "LBDesc1";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinText UIDescriptionLine1Text
        {
            get
            {
                if ((this.mUIDescriptionLine1Text == null))
                {
                    this.mUIDescriptionLine1Text = new WinText(this);
                    #region Search Criteria
                    this.mUIDescriptionLine1Text.SearchProperties[WinText.PropertyNames.Name] = "LBDesc1";
                    this.mUIDescriptionLine1Text.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
                    #endregion
                }
                return this.mUIDescriptionLine1Text;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIDescriptionLine1Text;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDescriptionLine2Window : WinWindow
    {
        
        public UIDescriptionLine2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "LBDesc2";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinText UIDescriptionLine2Text
        {
            get
            {
                if ((this.mUIDescriptionLine2Text == null))
                {
                    this.mUIDescriptionLine2Text = new WinText(this);
                    #region Search Criteria
                    this.mUIDescriptionLine2Text.SearchProperties[WinText.PropertyNames.Name] = "LBDesc2";
                    this.mUIDescriptionLine2Text.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
                    #endregion
                }
                return this.mUIDescriptionLine2Text;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIDescriptionLine2Text;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDisplayURLWindow : WinWindow
    {
        
        public UIDisplayURLWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "LBDisplayURL";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinText UIDisplayURLText
        {
            get
            {
                if ((this.mUIDisplayURLText == null))
                {
                    this.mUIDisplayURLText = new WinText(this);
                    #region Search Criteria
                    this.mUIDisplayURLText.SearchProperties[WinText.PropertyNames.Name] = "LBDisplayURL";
                    this.mUIDisplayURLText.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___KIwwo - ___Lyep5 - adSage for Performance");
                    #endregion
                }
                return this.mUIDisplayURLText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIDisplayURLText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIWss_adsagetest163comWindow3 : WinWindow
    {
        
        public UIWss_adsagetest163comWindow3()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIGoogleTextAdEditorWindow1 UIGoogleTextAdEditorWindow
        {
            get
            {
                if ((this.mUIGoogleTextAdEditorWindow == null))
                {
                    this.mUIGoogleTextAdEditorWindow = new UIGoogleTextAdEditorWindow1(this);
                }
                return this.mUIGoogleTextAdEditorWindow;
            }
        }
        
        public UITBHeadlineWindow1 UITBHeadlineWindow
        {
            get
            {
                if ((this.mUITBHeadlineWindow == null))
                {
                    this.mUITBHeadlineWindow = new UITBHeadlineWindow1(this);
                }
                return this.mUITBHeadlineWindow;
            }
        }
        
        public UITBDesc1Window1 UITBDesc1Window
        {
            get
            {
                if ((this.mUITBDesc1Window == null))
                {
                    this.mUITBDesc1Window = new UITBDesc1Window1(this);
                }
                return this.mUITBDesc1Window;
            }
        }
        
        public UITBDesc2Window1 UITBDesc2Window
        {
            get
            {
                if ((this.mUITBDesc2Window == null))
                {
                    this.mUITBDesc2Window = new UITBDesc2Window1(this);
                }
                return this.mUITBDesc2Window;
            }
        }
        
        public UITBDisplayWindow1 UITBDisplayWindow
        {
            get
            {
                if ((this.mUITBDisplayWindow == null))
                {
                    this.mUITBDisplayWindow = new UITBDisplayWindow1(this);
                }
                return this.mUITBDisplayWindow;
            }
        }
        
        public UICBStatusWindow1 UICBStatusWindow
        {
            get
            {
                if ((this.mUICBStatusWindow == null))
                {
                    this.mUICBStatusWindow = new UICBStatusWindow1(this);
                }
                return this.mUICBStatusWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleTextAdEditorWindow1 mUIGoogleTextAdEditorWindow;
        
        private UITBHeadlineWindow1 mUITBHeadlineWindow;
        
        private UITBDesc1Window1 mUITBDesc1Window;
        
        private UITBDesc2Window1 mUITBDesc2Window;
        
        private UITBDisplayWindow1 mUITBDisplayWindow;
        
        private UICBStatusWindow1 mUICBStatusWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIGoogleTextAdEditorWindow1 : WinWindow
    {
        
        public UIGoogleTextAdEditorWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "GoogleTextAdEditor";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UIButtonEditDestinatioEdit UIButtonEditDestinatioEdit
        {
            get
            {
                if ((this.mUIButtonEditDestinatioEdit == null))
                {
                    this.mUIButtonEditDestinatioEdit = new UIButtonEditDestinatioEdit(this);
                }
                return this.mUIButtonEditDestinatioEdit;
            }
        }
        #endregion
        
        #region Fields
        private UIButtonEditDestinatioEdit mUIButtonEditDestinatioEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIButtonEditDestinatioEdit : WinEdit
    {
        
        public UIButtonEditDestinatioEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinEdit.PropertyNames.Name] = "LBDestination";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UIButtonEditDestinatioEdit1
        {
            get
            {
                if ((this.mUIButtonEditDestinatioEdit1 == null))
                {
                    this.mUIButtonEditDestinatioEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUIButtonEditDestinatioEdit1.SearchProperties[WinEdit.PropertyNames.Name] = "LBDestination";
                    this.mUIButtonEditDestinatioEdit1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIButtonEditDestinatioEdit1.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUIButtonEditDestinatioEdit1;
            }
        }
        
        public WinEdit UILBDestinationEdit
        {
            get
            {
                if ((this.mUILBDestinationEdit == null))
                {
                    this.mUILBDestinationEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILBDestinationEdit.SearchProperties[WinEdit.PropertyNames.Name] = "LBDestination";
                    this.mUILBDestinationEdit.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUILBDestinationEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUILBDestinationEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIButtonEditDestinatioEdit1;
        
        private WinEdit mUILBDestinationEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBHeadlineWindow1 : WinWindow
    {
        
        public UITBHeadlineWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBHeadline";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBHeadlineEdit
        {
            get
            {
                if ((this.mUITBHeadlineEdit == null))
                {
                    this.mUITBHeadlineEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBHeadlineEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBHeadline";
                    this.mUITBHeadlineEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUITBHeadlineEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBHeadlineEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBDesc1Window1 : WinWindow
    {
        
        public UITBDesc1Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBDesc1";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBDesc1Edit
        {
            get
            {
                if ((this.mUITBDesc1Edit == null))
                {
                    this.mUITBDesc1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBDesc1Edit.SearchProperties[WinEdit.PropertyNames.Name] = "TBDesc1";
                    this.mUITBDesc1Edit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUITBDesc1Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBDesc1Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBDesc2Window1 : WinWindow
    {
        
        public UITBDesc2Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBDesc2";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBDesc2Edit
        {
            get
            {
                if ((this.mUITBDesc2Edit == null))
                {
                    this.mUITBDesc2Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBDesc2Edit.SearchProperties[WinEdit.PropertyNames.Name] = "TBDesc2";
                    this.mUITBDesc2Edit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUITBDesc2Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBDesc2Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITBDisplayWindow1 : WinWindow
    {
        
        public UITBDisplayWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TBDisplay";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinEdit UITBDisplayEdit
        {
            get
            {
                if ((this.mUITBDisplayEdit == null))
                {
                    this.mUITBDisplayEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITBDisplayEdit.SearchProperties[WinEdit.PropertyNames.Name] = "TBDisplay";
                    this.mUITBDisplayEdit.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUITBDisplayEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITBDisplayEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICBStatusWindow1 : WinWindow
    {
        
        public UICBStatusWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CBStatus";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICBStatusComboBox
        {
            get
            {
                if ((this.mUICBStatusComboBox == null))
                {
                    this.mUICBStatusComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICBStatusComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "CBStatus";
                    this.mUICBStatusComboBox.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUICBStatusComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICBStatusComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "16";
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public UINewItemRowRow UINewItemRowRow
        {
            get
            {
                if ((this.mUINewItemRowRow == null))
                {
                    this.mUINewItemRowRow = new UINewItemRowRow(this);
                }
                return this.mUINewItemRowRow;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UINewItemRowRow mUINewItemRowRow;
        
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UINewItemRowRow : WinRow
    {
        
        public UINewItemRowRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "NewItem Row";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinCell UIAdGrouprow2147483647Cell
        {
            get
            {
                if ((this.mUIAdGrouprow2147483647Cell == null))
                {
                    this.mUIAdGrouprow2147483647Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIAdGrouprow2147483647Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUIAdGrouprow2147483647Cell;
            }
        }
        
        public WinCell UIAdGroupStatusrow2147Cell
        {
            get
            {
                if ((this.mUIAdGroupStatusrow2147Cell == null))
                {
                    this.mUIAdGroupStatusrow2147Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIAdGroupStatusrow2147Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUIAdGroupStatusrow2147Cell;
            }
        }
        
        public WinCell UIDisplayURLrow2147483Cell
        {
            get
            {
                if ((this.mUIDisplayURLrow2147483Cell == null))
                {
                    this.mUIDisplayURLrow2147483Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIDisplayURLrow2147483Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUIDisplayURLrow2147483Cell;
            }
        }
        
        public WinCell UICampaignrow214748364Cell
        {
            get
            {
                if ((this.mUICampaignrow214748364Cell == null))
                {
                    this.mUICampaignrow214748364Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUICampaignrow214748364Cell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUICampaignrow214748364Cell;
            }
        }
        
        public WinCell UILocalStateExtensionrCell
        {
            get
            {
                if ((this.mUILocalStateExtensionrCell == null))
                {
                    this.mUILocalStateExtensionrCell = new WinCell(this);
                    #region Search Criteria
                    this.mUILocalStateExtensionrCell.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUILocalStateExtensionrCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIAdGrouprow2147483647Cell;
        
        private WinCell mUIAdGroupStatusrow2147Cell;
        
        private WinCell mUIDisplayURLrow2147483Cell;
        
        private WinCell mUICampaignrow214748364Cell;
        
        private WinCell mUILocalStateExtensionrCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemTable : WinTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
            #endregion
        }
        
        #region Properties
        public WinClient UIDataPanelClient
        {
            get
            {
                if ((this.mUIDataPanelClient == null))
                {
                    this.mUIDataPanelClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIDataPanelClient.SearchProperties[WinControl.PropertyNames.Name] = "Data Panel";
                    this.mUIDataPanelClient.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUIDataPanelClient;
            }
        }
        
        public WinClient UIHeaderPanelClient
        {
            get
            {
                if ((this.mUIHeaderPanelClient == null))
                {
                    this.mUIHeaderPanelClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIHeaderPanelClient.SearchProperties[WinControl.PropertyNames.Name] = "Header Panel";
                    this.mUIHeaderPanelClient.WindowTitles.Add("wss_adsagetest@163.com(CNY) - ___8xxfHM - ___OZ7a_2 - adSage for Performance");
                    #endregion
                }
                return this.mUIHeaderPanelClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIDataPanelClient;
        
        private WinClient mUIHeaderPanelClient;
        #endregion
    }
}
