// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Facebook.UITestFramework.UIMaps.ChooseCampaignWindowClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public partial class ChooseCampaignWindow
    {
        
        #region Properties
        public UIChooseaCampaignWindow UIChooseaCampaignWindow
        {
            get
            {
                if ((this.mUIChooseaCampaignWindow == null))
                {
                    this.mUIChooseaCampaignWindow = new UIChooseaCampaignWindow();
                }
                return this.mUIChooseaCampaignWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIChooseaCampaignWindow mUIChooseaCampaignWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIChooseaCampaignWindow : WinWindow
    {
        
        public UIChooseaCampaignWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Choose a Campaign";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Choose a Campaign");
            #endregion
        }
        
        #region Properties
        public UIParentLocalizerWindow UIParentLocalizerWindow
        {
            get
            {
                if ((this.mUIParentLocalizerWindow == null))
                {
                    this.mUIParentLocalizerWindow = new UIParentLocalizerWindow(this);
                }
                return this.mUIParentLocalizerWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIParentLocalizerWindow mUIParentLocalizerWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIParentLocalizerWindow : WinWindow
    {
        
        public UIParentLocalizerWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "ParentLocalizer";
            this.WindowTitles.Add("Choose a Campaign");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICampaignComboBox
        {
            get
            {
                if ((this.mUICampaignComboBox == null))
                {
                    this.mUICampaignComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICampaignComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Campaign:";
                    this.mUICampaignComboBox.WindowTitles.Add("Choose a Campaign");
                    #endregion
                }
                return this.mUICampaignComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICampaignComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "BTOK";
            this.WindowTitles.Add("Choose a Campaign");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Choose a Campaign");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
